CREATE DATABASE DB_innovatube;
USE DB_innovatube;

GO
CREATE TABLE Users(
	Id INT PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(100) UNIQUE NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	Username NVARCHAR(100) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	accessPassword NVARCHAR(255) NOT NULL,
	FirstLogin BIT,
	statusUser NVARCHAR(20) NOT NULL,
	CreatedAt DATETIME DEFAULT GETDATE()
);

GO
CREATE TABLE Videos(
	IdVideo NVARCHAR(100) PRIMARY KEY,
	Title NVARCHAR(255),
	ThumbnailUrl NVARCHAR(255),
	PublishedAt DATETIME
)

GO
CREATE TABLE UserFavoriteVideos (
    Id INT PRIMARY KEY IDENTITY(1,1),
    UserId INT NOT NULL,
    VideoId NVARCHAR(100) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),

    FOREIGN KEY (UserId) REFERENCES Users(Id),
    FOREIGN KEY (VideoId) REFERENCES Videos(IdVideo),
    CONSTRAINT UC_UserVideo UNIQUE (UserId, VideoId)
);

GO
CREATE TABLE PasswordResetTokens (
    Id INT PRIMARY KEY IDENTITY,
    Email NVARCHAR(100) NOT NULL,
    Token NVARCHAR(255) NOT NULL,
    Expiration DATETIME NOT NULL,
    Used BIT DEFAULT 0
);
